version: "3.9"
services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - EXTERNAL_API_URL=
      - EXTERNAL_API_KEY=
      - EXTERNAL_API_LANGUAGE=
      - DB_USERNAME=
      - DB_PASSWORD=
      - DB_URL=
