name: What-s-up-doc-API

on:
  push:
    branches: [ feature/deploy ]

jobs:
  api:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout project
        uses: actions/checkout@v2
      -
        name: Maven tests
        run: |
          mvn clean test
      -
        name: Maven build
        run: |
          mvn clean package
      -
        name: Docker build
        run: |
          docker build -t whatsupdockproject/whatsupdoc-api:latest .
      -
        name: Push previous image on DockerHub
        run: |
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login $DOCKER_REGISTRY --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker push whatsupdockproject/whatsupdoc-api:latest

  deploy:
    runs-on: ubuntu-latest
    needs: [api]

    steps:
      -
        name: Azure login
        run: |
          az login -u ${{ secrets.AZ_LOGIN }} -p ${{ secrets.AZ_PASSWORD }}
      - name: Azure deploy service
        run: |
          az webapp config container set --name ${{ secrets.AZ_APP_NAME }} --resource-group ${{ secrets.AZ_RG_NAME }} --docker-custom-image-name whatsupdockproject/whatsupdoc-api:latest
      -
        name: Azure restart service
        run: |
          az webapp restart --name ${{ secrets.AZ_APP_NAME }} --resource-group ${{ secrets.AZ_RG_NAME }}
      -
        name: Azure logout
        run: |
          az logout